### ISSUE TITLE
OpenTelemetry integration async error

### ISSUE THREAD

**Issue by elijahbenizzy** [apache/burr#413]
**Is your feature request related to a problem? Please describe.**

```bash
wt-api   |     |   File "/usr/local/lib/python3.11/site-packages/burr/integrations/opentelemetry.py", line 499, in on_end
wt-api   |     |     self.tracker.post_end_span(
wt-api   |     |     ^^^^^^^^^^^^^^^^^^^^^^^^^^
wt-api   |     | AttributeError: 'NoneType' object has no attribute 'post_end_span'
```

Comes up -- it appears to be non-blocking. @mdrideout investigated/figured this out. See conversation here: https://discord.com/channels/1221891403253288970/1260781251078656063/1301698093556699156.

**Describe the solution you'd like**
We should investigate and fix.

**Describe alternatives you've considered**
Likely not immediate (@mdrideout to confirm) but worth investigating.

**Comment by mdrideout** [comment]
Confirming this still functions as intended and the workflow completes. Non-blocking exception.

**Comment by andreahlert** [comment]
@elijahbenizzy @skrawcz Tested on Docker (Python 3.11) with latest source, fix from #590 works. Safe to close.

**Comment by andreahlert** [comment]
Labels migrated to new taxonomy (#692).

**Comment by andreahlert** [comment]
Resolved by #590 (merged Nov 2025). Confirmed working on Docker/Python 3.11.
